# Generated by Django 2.0a1 on 2017-09-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_symbols'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symbols',
        ),
        migrations.AddField(
            model_name='quiz',
            name='symbols',
            field=models.CharField(default='&hearts;', max_length=100),
            preserve_default=False,
        ),
    ]
